# Generated by Django 4.0.6 on 2022-07-21 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=300, verbose_name='Название категории')),
                ('category_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_author', models.CharField(max_length=500, verbose_name='Автор')),
                ('book_work', models.CharField(max_length=500, verbose_name='Произведение')),
                ('book_description', models.TextField(verbose_name='Описание')),
                ('book_price', models.FloatField(verbose_name='Цена')),
                ('book_photo', models.ImageField(upload_to='', verbose_name='Обложка книги')),
                ('book_quantity', models.IntegerField(blank=True, null=True, verbose_name='Количество')),
                ('book_date', models.DateTimeField(auto_now_add=True)),
                ('book_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.category')),
            ],
        ),
    ]
