# Generated by Django 4.0.6 on 2022-07-24 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_book_options_alter_category_options_book_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.CharField(blank=True, default='bla bla', max_length=100, null=True, unique=True, verbose_name='url'),
        ),
    ]
